"""FINANCE_TOOLS 定义 + Handler 注册表"""
from handlers import (
    add_record, add_income, set_budget, update_budget,
    analyze_spend, add_category, delete_category,
    budget_remain, delete_budget, suggest_budgets,
    query_income, category_sum, search_records,
    delete_record, delete_income,
)

handlers = {
    "add_record": add_record,
    "add_income": add_income,
    "set_budget": set_budget,
    "update_budget": update_budget,
    "analyze_spend": analyze_spend,
    "add_category": add_category,
    "delete_category": delete_category,
    "budget_remain": budget_remain,
    "delete_budget": delete_budget,
    "suggest_budgets": suggest_budgets,
    "query_income": query_income,
    "category_sum": category_sum,
    "search_records": search_records,
    "delete_record": delete_record,
    "delete_income": delete_income,
}

FINANCE_TOOLS = [
    {"type": "function", "function": {"name": "add_record", "description": "记录一笔支出",
        "parameters": {"type": "object", "required": ["分类", "金额"],
            "properties": {"分类": {"type": "string"}, "金额": {"type": "number"},
                           "备注": {"type": "string"}, "时间": {"type": "string", "description": "YYYY-MM-DD，默认今天"}}}}},
    {"type": "function", "function": {"name": "add_income", "description": "记录一笔收入",
        "parameters": {"type": "object", "required": ["分类", "金额"],
            "properties": {"分类": {"type": "string"}, "金额": {"type": "number"},
                           "备注": {"type": "string"}, "时间": {"type": "string", "description": "YYYY-MM-DD，默认今天"}}}}},
    {"type": "function", "function": {"name": "set_budget", "description": "设置某分类的月预算",
        "parameters": {"type": "object", "required": ["分类", "金额"],
            "properties": {"分类": {"type": "string"}, "金额": {"type": "number"},
                           "月份": {"type": "string", "description": "YYYY-MM，默认当月"}}}}},
    {"type": "function", "function": {"name": "update_budget", "description": "更新某分类的月预算",
        "parameters": {"type": "object", "required": ["分类", "金额"],
            "properties": {"分类": {"type": "string"}, "金额": {"type": "number"},
                           "月份": {"type": "string"}}}}},
    {"type": "function", "function": {"name": "delete_budget", "description": "删除某分类某月份的预算",
        "parameters": {"type": "object", "required": ["分类"],
            "properties": {"分类": {"type": "string", "description": "要删除预算的支出分类名"},
                           "月份": {"type": "string", "description": "YYYY-MM，不填则为本月"}}}}},
    {"type": "function", "function": {"name": "analyze_spend", "description": "整体消费分析，生成消费排行、收入排行和建议",
        "parameters": {"type": "object",
            "properties": {"月份": {"type": "string", "description": "YYYY-MM，默认当月"}}}}},
    {"type": "function", "function": {"name": "add_category", "description": "新增支出或收入分类",
        "parameters": {"type": "object", "required": ["分类"],
            "properties": {"分类": {"type": "string"},
                           "类型": {"type": "string", "enum": ["支出", "收入"]}}}}},
    {"type": "function", "function": {"name": "delete_category", "description": "删除分类及其所有记录",
        "parameters": {"type": "object", "required": ["分类"],
            "properties": {"分类": {"type": "string"}}}}},
    {"type": "function", "function": {"name": "budget_remain", "description": "查询预算剩余",
        "parameters": {"type": "object",
            "properties": {"月份": {"type": "string", "description": "YYYY-MM，默认当月"},
                           "分类": {"type": "string", "description": "留空返回全部分类"}}}}},
    {"type": "function", "function": {"name": "suggest_budgets", "description": "根据历史消费智能推荐预算",
        "parameters": {"type": "object",
            "properties": {"总预算": {"type": "number"}}}}},
    {"type": "function", "function": {"name": "query_income", "description": "查询收入记录",
        "parameters": {"type": "object",
            "properties": {"分类": {"type": "string"}, "时间范围": {"type": "string"},
                           "全部": {"type": "string", "enum": ["是", "否"]}}}}},
    {"type": "function", "function": {"name": "category_sum", "description": "统计某分类或时间段的支出总额",
        "parameters": {"type": "object",
            "properties": {"分类": {"type": "string"},
                           "开始时间": {"type": "string", "description": "YYYY-MM-DD"},
                           "结束时间": {"type": "string", "description": "YYYY-MM-DD"}}}}},
    {"type": "function", "function": {"name": "search_records", "description": "查询支出明细列表（含记录ID），可按分类、时间、备注关键词筛选。删除前先调用此接口查看实际记录",
        "parameters": {"type": "object",
            "properties": {"分类": {"type": "string", "description": "支出分类，留空返回全部"},
                           "时间范围": {"type": "string", "description": "YYYY-MM-DD（某天）、YYYY-MM（某月）或YYYY（某年），留空返回最近记录"},
                           "关键词": {"type": "string", "description": "备注关键词，模糊匹配，如'麦当劳'、'滴滴'"},
                           "条数": {"type": "integer", "description": "返回条数，默认10，最多20"}}}}},
    {"type": "function", "function": {"name": "delete_record", "description": "按记录ID删除一条支出记录。请先用 search_records 查询获取ID再调用此接口",
        "parameters": {"type": "object", "required": ["记录ID"],
            "properties": {"记录ID": {"type": "integer", "description": "支出记录的唯一ID"}}}}},
    {"type": "function", "function": {"name": "delete_income", "description": "按记录ID删除一条收入记录。请先用 query_income（全部=是）查询获取ID再调用",
        "parameters": {"type": "object", "required": ["收入ID"],
            "properties": {"收入ID": {"type": "integer", "description": "收入记录的唯一ID"}}}}},
]
